### PR TITLE
Factor token provider out into a separate trait

### PR DESCRIPTION
**Pull request by djc**
I ran into https://github.com/dermesser/yup-oauth2/issues/137. In general, making the authentication/authorization process more explicit in the type system seems like a good idea (in a future PR, the `YupAuthorizer` and dependency could become optional).

### CODE REVIEW

**Comment by djc** [comment]
My work project is now using a different `Authorizer` impl instead, based on the [gcp_auth](https://crates.io/crates/gcp_auth) crate. It has a more minimal API, which makes it easier to use for our purposes. I could add my (equally optional) gcp_auth-based implementation to this crate as well, if you think that makes sense.

**Review by ErichDonGubler — COMMENTED** [review]
It makes me scratch my head that the feature flag actually being evaluated inside of `src/` is `yup-oauth2`, because distinguishing between `yup-oauth2` and the newly added `yup-authorizer` flag seems like a distinction that does more harm than good. `hyper-rustls` is necessary for code enabled with `cfg(feature = "yup-oauth2")` to compile, and the compilation failures don't give great diagnostics. This all would get obviated by just checking `cfg(feature = yup-authorizer)` instead.

Did you have a concrete benefit in mind for using flags this way that I'm not seeing?

**Comment by djc** [comment]
> Did you have a concrete benefit in mind for using flags this way that I'm not seeing?

Not really, I tend to want to use the "smallest" feature guard so that if you add more complex feature dependencies later on, stuff is a little easier. I changed all of the feature guards to `yup-authorizer` for now.

**Comment by djc** [comment]
Rebased this on top of current master.

**Comment by Xaeroxe** [comment]
:clap: Nicely done!

> I could add my (equally optional) gcp_auth-based implementation to this crate as well, if you think that makes sense.

Yes, I think that makes a lot of sense. It might even be appropriate to make it the default authorizer?

**Comment by djc** [comment]
> Yes, I think that makes a lot of sense. It might even be appropriate to make it the default authorizer?

I'd certainly prefer it!

**Comment by Xaeroxe** [comment]
Great, let's do that in a follow up PR. I'd like to get this one merged. As for whether or not it should be the default, I'd like to make that choice after I see what data is required to build that authorizer

**Comment by djc** [comment]
Sounds good to me.

**Pull request merged**
